version: "3.5"
services:
  redis:
    container_name: redis
    image: redis
    ports: 
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - my-network
  coinph-worker:
    container_name: coinph-worker
    image: coinph-worker
    env_file:
      - ./.env
    restart: always
    command: node index.js
    depends_on:
      - redis
    networks:
      - my-network

volumes:
  redis-data:
    driver: local

networks:
  my-network:
    name: my-network 
